### ISSUE TITLE
Curved and Dynamic Height properties are not persisted correctly.

### ISSUE THREAD

**Issue by cri5ti** [DevExpress/dashboard-extension-funnel-d3-item#2]
If you use the funnel extension in a dashboard and set the Curved or Dynamic Height it doesn't restore correctly from the XML.

Here's the related XML fragment:

```
<CustomMetadata FillType="Gradient" IsCurved="true" IsDynamicHeight="false" PinchCount="1">
	<Values>
	    <Item1 ItemType="Measure" DefaultId="DataItem0" />
	</Values>
	<Arguments>
	    <Item1 ItemType="Dimension" DefaultId="DataItem1" />
	</Arguments>
</CustomMetadata>
```

Is the metadata correct?
Aren't the values being restored as strings instead of bools?

        propertyName: 'IsDynamicHeight',
        editor: DevExpress.Dashboard.Metadata.editorTemplates.boolYesNo,
        displayName: 'DashboardWebCustomItemStringId.IsDynamicHeight',
        sectionName: 'DashboardWebCustomItemStringId.SectionName',
        defaultVal: true

**Comment by poltp** [comment]
Thanks for your report. I see the issue. I will fix it ASAP.
